<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'category_id' => 1,
                'name' => 'Cotton T-Shirt',
                'name_tm' => 'Pagta futbolka',
                'name_ru' => 'Хлопковая футболка',
                'description' => 'High quality 100% cotton t-shirt.',
                'description_tm' => 'Ýokary hilli 100% pagta futbolka.',
                'description_ru' => 'Высококачественная футболка из 100% хлопка.',
                'shop' => 'LC Waikiki',
                'view_count' => 4089,
                'like_count' => 3087,
                'price' => 15.99,
                'stock' => 50,
            ],
            [
                'category_id' => 1,
                'name' => 'Denim Jacket',
                'name_tm' => 'Jinsy kurtka',
                'name_ru' => 'Джинсовая куртка',
                'description' => 'Classic blue denim jacket.',
                'description_tm' => 'Klassiki gök jinsy kurtka.',
                'description_ru' => 'Классическая синяя джинсовая куртка.',
                'shop' => 'Berkarar Shop',
                'view_count' => 8089,
                'like_count' => 5087,
                'price' => 45.50,
                'stock' => 20,
            ],
            [
                'category_id' => 3,
                'name' => 'Smartphone Pro 15',
                'name_tm' => 'Smartfon Pro 15',
                'name_ru' => 'Смартфон Pro 15',
                'description' => 'Latest model with triple camera.',
                'description_tm' => 'Üç kameraly iň täze model.',
                'description_ru' => 'Последняя модель с тройной камерой.',
                'shop' => 'Sumbar Computer',
                'view_count' => 5089,
                'like_count' => 2087,
                'price' => 999.00,
                'stock' => 10,
            ],
            [
                'category_id' => 3,
                'name' => 'Wireless Headphones',
                'name_tm' => 'Simsiz nauşniklar',
                'name_ru' => 'Беспроводные наушники',
                'description' => 'Noise cancelling bluetooth headphones.',
                'description_tm' => 'Goşundy kesýän bluetooth nauşniklar.',
                'description_ru' => 'Bluetooth наушники с шумоподавлением.',
                'shop' => 'Satuw TM',
                'view_count' => 4089,
                'like_count' => 4087,
                'price' => 120.00,
                'stock' => 35,
            ],
            [
                'category_id' => 2,
                'name' => 'Running Sneakers',
                'name_tm' => 'Ylgaw köwüşleri',
                'name_ru' => 'Кроссовки для бега',
                'description' => 'Lightweight breathable sneakers.',
                'description_tm' => 'Ýeňil we howa geçirýän krossowkalar.',
                'description_ru' => 'Легкие дышащие кроссовки.',
                'shop' => 'Sport Store',
                'view_count' => 8089,
                'like_count' => 7087,
                'price' => 65.00,
                'stock' => 25,
            ],
            [
                'category_id' => 5,
                'name' => 'Ceramic Flower Pot',
                'name_tm' => 'Keramika gül gabysy',
                'name_ru' => 'Керамический горшок',
                'description' => 'Handmade ceramic pot for plants.',
                'description_tm' => 'Ösümlikler üçin elde ýasalan keramika gaby.',
                'description_ru' => 'Керамический горшок ручной работы.',
                'shop' => 'Gül Zaman',
                'view_count' => 5089,
                'like_count' => 2087,
                'price' => 12.50,
                'stock' => 100,
            ],
            [
                'category_id' => 4,
                'name' => 'Gaming Mouse RGB',
                'name_tm' => 'Oýun syçanjygy RGB',
                'name_ru' => 'Игровая мышь RGB',
                'description' => 'High-precision optical sensor with 16000 DPI.',
                'description_tm' => '16000 DPI ýokary takyklykly optiki datçik.',
                'description_ru' => 'Высокоточный оптический сенсор 16000 DPI.',
                'shop' => 'Sumbar Computer',
                'view_count' => 5089,
                'like_count' => 4087,
                'price' => 45.00,
                'stock' => 150,
            ],
            [
                'category_id' => 3,
                'name' => 'Smart Watch Series 7',
                'name_tm' => 'Akylly sagat Series 7',
                'name_ru' => 'Смарт-часы Series 7',
                'description' => 'Water resistant with heart rate monitor.',
                'description_tm' => 'Suwa durnukly we ýürek urşuny ölçeýän.',
                'description_ru' => 'Водонепроницаемые с монитором пульса.',
                'shop' => 'Electronics TM',
                'view_count' => 4089,
                'like_count' => 3087,
                'price' => 199.99,
                'stock' => 40,
            ],
            [
                'category_id' => 3,
                'name' => 'Power Bank 20000mAh',
                'name_tm' => 'Daşarky akkumulýator 20000mAh',
                'name_ru' => 'Повербанк 20000мАч',
                'description' => 'Fast charging portable power bank.',
                'description_tm' => 'Çalt zarýad berýän göçme akkumulýator.',
                'description_ru' => 'Портативный аккумулятор с быстрой зарядкой.',
                'shop' => 'Satuw TM',
                'view_count' => 4089,
                'like_count' => 3087,
                'price' => 35.50,
                'stock' => 80,
            ],
            [
                'category_id' => 6,
                'name' => 'Electric Kettle',
                'name_tm' => 'Elektriki çaýnek',
                'name_ru' => 'Электрический чайник',
                'description' => 'Stainless steel 1.7L electric kettle.',
                'description_tm' => 'Poslamaýan polatdan 1.7L elektriki çaýnek.',
                'description_ru' => 'Чайник из нержавеющей стали 1.7л.',
                'shop' => 'Kamil Market',
                'view_count' => 1005,
                'like_count' => 1000,
                'price' => 29.00,
                'stock' => 60,
            ],
            [
                'category_id' => 6,
                'name' => 'Coffee Maker',
                'name_tm' => 'Kofe maşyny',
                'name_ru' => 'Кофеварка',
                'description' => 'Automatic espresso machine.',
                'description_tm' => 'Awtomatiki espresso maşyny.',
                'description_ru' => 'Автоматическая эспрессо-машина.',
                'shop' => 'Kamil Market',
                'view_count' => 8005,
                'like_count' => 7009,
                'price' => 150.00,
                'stock' => 15,
            ],
            [
                'category_id' => 7,
                'name' => 'Hair Dryer',
                'name_tm' => 'Fen (saç guradyjy)',
                'name_ru' => 'Фен для волос',
                'description' => 'Professional hair dryer with ionic technology.',
                'description_tm' => 'Professional saç guradyjy.',
                'description_ru' => 'Профессиональный фен с ионизацией.',
                'shop' => 'Merjen Beauty',
                'view_count' => 7090,
                'like_count' => 6788,
                'price' => 55.00,
                'stock' => 45,
            ],
            [
                'category_id' => 7,
                'name' => 'Electric Toothbrush',
                'name_tm' => 'Elektriki diş çetkasy',
                'name_ru' => 'Электрическая зубная щетка',
                'description' => 'Rechargeable sonic toothbrush.',
                'description_tm' => 'Zarýad berilýän sesli diş çetkasy.',
                'description_ru' => 'Перезаряжаемая звуковая щетка.',
                'shop' => 'Magazine 7',
                'view_count' => 1008,
                'like_count' => 998,
                'price' => 85.00,
                'stock' => 100,
            ],
            [
                'category_id' => 16,
                'name' => 'Handmade Wool Carpet',
                'name_tm' => 'Elde dokalan ýüň haly',
                'name_ru' => 'Шерстяной ковёр ручной работы',
                'description' => 'High-quality traditional carpet made of natural wool.',
                'description_tm' => 'Tebigy ýüňden dokalan ýokary hilli adaty haly.',
                'description_ru' => 'Высококачественный традиционный ковёр из натуральной шерсти.',
                'shop' => 'Online Shop',
                'view_count' => 8045,
                'like_count' => 2007,
                'price' => 10000.00,
                'stock' => 15,
            ],
            [
                'category_id' => 8,
                'name' => 'Dumbbells Set 10kg',
                'name_tm' => 'Gantel toplumy 10kg',
                'name_ru' => 'Набор гантелей 10кг',
                'description' => 'Pair of adjustable dumbbells.',
                'description_tm' => 'Sazlanyp bilinýän ganteller.',
                'description_ru' => 'Пара регулируемых гантелей.',
                'shop' => 'Magazine 3',
                'view_count' => 4009,
                'like_count' => 4004,
                'price' => 40.00,
                'stock' => 30,
            ],
            [
                'category_id' => 9,
                'name' => 'LEGO Star Wars Set',
                'name_tm' => 'LEGO Star Wars toplumy',
                'name_ru' => 'Конструктор LEGO Star Wars',
                'description' => 'Building blocks for kids and collectors.',
                'description_tm' => 'Çagalar we ýygnaýjylar üçin konstruktor.',
                'description_ru' => 'Конструктор для детей и коллекционеров.',
                'shop' => 'Toy World TM',
                'view_count' => 1005,
                'like_count' => 1000,
                'price' => 99.00,
                'stock' => 25,
            ],
            [
                'category_id' => 10,
                'name' => 'Car Phone Holder',
                'name_tm' => 'Awtoulag telefon saklaýjysy',
                'name_ru' => 'Держатель для телефона в авто',
                'description' => 'Magnetic dashboard phone mount.',
                'description_tm' => 'Magnitli awtoulag telefon saklaýjysy.',
                'description_ru' => 'Магнитный держатель на панель.',
                'shop' => 'Auto Zone',
                'view_count' => 6005,
                'like_count' => 6000,
                'price' => 12.00,
                'stock' => 300,
            ],
            [
                'category_id' => 11,
                'name' => 'Leather Wallet',
                'name_tm' => 'Deri gapjyk',
                'name_ru' => 'Кожаный кошелек',
                'description' => 'Genuine leather men wallet.',
                'description_tm' => 'Hakyky deriden erkek gapjygy.',
                'description_ru' => 'Мужской кошелек из натуральной кожи.',
                'shop' => 'Asman Fashion',
                'view_count' => 7005,
                'like_count' => 6067,
                'price' => 30.00,
                'stock' => 55,
            ],
            [
                'category_id' => 11,
                'name' => 'Sunglasses UV400',
                'name_tm' => 'Günüň äýnegi UV400',
                'name_ru' => 'Солнцезащитные очки UV400',
                'description' => 'Polarized lenses for eye protection.',
                'description_tm' => 'Gözleri goramak üçin polýarizirlenen äýnek.',
                'description_ru' => 'Поляризованные линзы для защиты глаз.',
                'shop' => 'Prestige TM',
                'view_count' => 5005,
                'like_count' => 5001,
                'price' => 25.00,
                'stock' => 75,
            ],
            [
                'category_id' => 15,
                'name' => 'Cat Food 2kg',
                'name_tm' => 'Pişik iými 2kg',
                'name_ru' => 'Корм для кошек 2кг',
                'description' => 'Premium dry food for adult cats.',
                'description_tm' => 'Uly pişikler üçin premium gury iým.',
                'description_ru' => 'Сухой корм премиум класса для кошек.',
                'shop' => 'Halk Market',
                'view_count' => 1005,
                'like_count' => 1000,
                'price' => 18.50,
                'stock' => 90,
            ],
            [
                'category_id' => 5,
                'name' => 'Blackout Curtains',
                'name_tm' => 'Güneş geçirmeýän perdeler',
                'name_ru' => 'Шторы блэкаут (светонепроницаемые)',
                'description' => 'Modern blackout curtains.',
                'description_tm' => 'Günüň şöhlesini saklaýan döwrebap zanaweskalar.',
                'description_ru' => 'Современные шторы блэкаут.',
                'shop' => 'Ak Tam Home',
                'view_count' => 5420,
                'like_count' => 1250,
                'price' => 85.00,
                'stock' => 45,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}